name: Report a module issue
description: Report a compatibility problem
body:
  - type: input
    id: module
    attributes:
      label: Module name
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue
    validations:
      required: true
